<a href="https://colab.research.google.com/github/brahmanarman01/Data_Science_Practice/blob/pandas/5_data_cleaningandprepocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# Imports the pandas library, which is used for data manipulation and analysis.

In [15]:
df=pd.read_csv('/content/1745501008647-data_cleaning_sample.csv')
# Reads the CSV file into a pandas DataFrame named 'df'.

In [16]:
df
# Displays the entire DataFrame 'df'.

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [17]:
df.isnull()
# Checks for null (missing) values in each cell of the DataFrame and returns a boolean DataFrame of the same shape.

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [18]:
df.isnull().sum()
# Calculates and displays the sum of null values for each column in the DataFrame.

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [19]:
df2=df
# Creates a copy of the DataFrame 'df' and assigns it to 'df2'.

In [20]:
df2
# Displays the entire DataFrame 'df2'.

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [21]:
df2.dropna()
# Drops rows with any null values from 'df2' and displays the result (does not modify 'df2' in place).

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [22]:
df2.dropna(axis=1)
# Drops columns with any null values from 'df2' and displays the result (does not modify 'df2' in place).

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [23]:
df2.fillna(0)
# Fills all null values in 'df2' with 0 and displays the result (does not modify 'df2' in place).

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [24]:
df2["Age"].fillna(df2["Age"].mean())
# Fills null values in the 'Age' column of 'df2' with the mean of the 'Age' column and displays the result (does not modify 'df2' in place).

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [25]:
df2.ffill()
# Fills null values using the forward fill method (propagates the last valid observation forward) and displays the result (does not modify 'df2' in place).

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [26]:
df2.bfill()
# Fills null values using the backward fill method (propagates the next valid observation backward) and displays the result (does not modify 'df2' in place).

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [27]:
df2.duplicated()
# Checks for duplicate rows in 'df2' and returns a boolean Series.

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [28]:
df2.drop_duplicates()
# Drops duplicate rows from 'df2' and displays the result (does not modify 'df2' in place).

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [29]:
df.duplicated(subset=["Name", "Age"])
# Checks for duplicate rows based on the 'Name' and 'Age' columns in 'df' and returns a boolean Series.

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [30]:
df["City"].str.contains("delhi", case=False)
# Checks if the 'City' column contains the string "delhi" (case-insensitive) and returns a boolean Series.

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [31]:
df["Email"].str.split("@")
# Splits the strings in the 'Email' column by the "@" symbol and returns a list of strings for each row.

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [32]:
# We can always chain methods like .str.strip().str.upper() for clean-up.
# This is a comment indicating that string methods can be chained for data cleaning.

In [33]:
df2['Age'].dtypes
# Displays the data type of the 'Age' column in 'df2'.

dtype('float64')

In [34]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x >= 18 else "Minor")
# Creates a new column 'Age Group' based on the 'Age' column, categorizing individuals as "Adult" or "Minor".
df["Age Group"]
# Displays the 'Age Group' column.

0    Adult
1    Minor
2    Adult
3    Minor
4    Adult
5    Adult
6    Adult
7    Adult
8    Minor
Name: Age Group, dtype: object

In [35]:
gender_map = {"M": "Male", "F": "Female"}
# Creates a dictionary to map gender abbreviations to full names.
df["Gender"] = df["Gender"].map(gender_map)
# Maps the values in the 'Gender' column using the 'gender_map' dictionary.

In [36]:
df[
    'Gender'
]
# Displays the 'Gender' column after mapping the values.

0    Female
1      Male
2      Male
3      Male
4      Male
5    Female
6    Female
7    Female
8      Male
Name: Gender, dtype: object

In [37]:
df["City"].replace({"Del": "Delhi", "Mum": "Mumbai"})
# Replaces "Del" with "Delhi" and "Mum" with "Mumbai" in the 'City' column (does not modify the column in place).
df["City"]
# Displays the 'City' column.

0       New York
1          Delhi
2    Los Angeles
3          Delhi
4         Mumbai
5          Delhi
6       New York
7       New York
8          Delhi
Name: City, dtype: object